const productsToInsert = [
  {
    name: "Fenel Infused Salt",
    id: 1,
    img: "../images/saltsimages/fenel infused salt.jpg",
    quantity: 1,
    price: "5$",
    image: "Fenel Infused Salt.jpg",
  },
  {
    name: "Citrus Infused Salt",
    id: 2,
    img: "../images/saltsimages/Citrus infused salt.jpg",
    quantity: 1,
    price: "6$",
    image: "Citrus_infused_salt.jpg",
  },
  {
    name: "Fenel Lemon Salt",
    id: 3,
    img: "../images/saltsimages/fenel-lemon-salt.jpg",
    quantity: 1,
    price: "5$",
    image: "fenel-lemon-salt.jpg",
  },
  {
    name: "Lemon Coriander Salt",
    id: 4,
    img: "../images/saltsimages/Lemon coriander salt.jpg",
    quantity: 1,
    price: "4$",
    image: "Lemon coriander salt.jpg",
  },
  {
    name: "Lemon and Black-pepper Salt",
    id: 5,
    img: "../images/saltsimages/lemon&black-pepper salt.jpg",
    quantity: 1,
    price: "6$",
    image: "lemon black-pepper salt.jpg",
  },
  {
    name: "Orange Infused Salt",
    id: 6,
    img: "../images/saltsimages/orange infused salt.jpg",
    quantity: 1,
    price: "8$",
    image: "orange infused salt.jpg",
  },
  {
    name: "Spicy Garlic Salt",
    id: 7,
    img: "../images/saltsimages/spicy-garlic-salt.jpg",
    quantity: 1,
    price: "7$",
    image: "spicy-garlic-salt.jpg",
  },
  {
    name: "Thyme Infused Salt",
    id: 8,
    img: "../images/saltsimages/thyme infused salt.jpg",
    quantity: 1,
    price: "6$",
    image: "thyme infused salt.jpg",
  },
  {
    name: "Tomato and Herbs Infused Salt",
    id: 9,
    img: "../images/saltsimages/tomato and herbs infused salt.jpg",
    quantity: 1,
    price: "5$",
    image: "tomato and herbs infused salt.jpg",
  },
  {
    name: "Ginger Lemon-leaves Salt",
    id: 10,
    img: "../images/saltsimages/Ginger Lemon Leaves salt.jpg",
    quantity: 1,
    price: "7$",
    image: "Ginger Lemon Leaves salt.jpg",
  },
  {
    name: "Lavender Infused Salt",
    id: 11,
    img: "../images/saltsimages/lavender infused salt.jpg",
    quantity: 1,
    price: "6$",
    image: "lavender infused salt.jpg",
  },
  {
    name: "Rose Infused Salt",
    id: 12,
    img: "../images/saltsimages/rose-infused-salt (2).jpg",
    quantity: 1,
    price: "4$",
    image: "rose-infused-salt (2).jpg",
  },
  {
    name: "Wine Infused Salt",
    id: 13,
    img: "../images/saltsimages/wine infused salt.jpg",
    quantity: 1,
    price: "5$",
    image: "wine infused salt.jpg",
  },
  {
    name: "Spicy Salt",
    id: 14,
    img: "../images/saltsimages/spicy salt.jpg",
    quantity: 1,
    price: "6$",
    image: "spicy salt.jpg",
  },
  {
    name: "Beetroot",
    id: 15,
    img: "../images/fleurDeSel/Beetroot.jpg",
    quantity: 1,
    price: "5$",
    image: "Beetroot.jpg",
  },
  {
    name: "Chili-Flakes",
    id: 16,
    img: "../images/fleurDeSel/Chili-Flakes.jpg",
    quantity: 1,
    price: "7$",
    image: "Chili-Flakes.jpg",
  },
  {
    name: "Fresh-Black-Pepper",
    id: 17,
    img: "../images/fleurDeSel/Fresh_Black_Pepper.jpg",
    quantity: 1,
    price: "8$",
    image: "Fresh_Black_Pepper.jpg",
  },
  {
    name: "Lavender",
    id: 18,
    img: "../images/fleurDeSel/Lavender.jpg",
    quantity: 1,
    price: "6$",
    image: "Lavender.jpg",
  },
  {
    name: "Tomato",
    id: 19,
    img: "../images/fleurDeSel/Tomato.jpg",
    quantity: 1,
    price: "8$",
    image: "Tomato.jpg",
  },
  {
    name: "Turmeric",
    id: 20,
    img: "../images/fleurDeSel/Turmeric.jpg",
    quantity: 1,
    price: "5$",
    image: "Turmeric.jpg",
  },
  {
    name: "Wine",
    id: 21,
    img: "../images/fleurDeSel/Wine.jpg",
    quantity: 1,
    price: "6$",
    image: "Wine.jpg",
  },

  {
    name: "Apple Chutney",
    id: 22,
    img: "../images/sauces/Apple Chutney.jpg",
    quantity: 1,
    price: "5$",
    image: "Apple Chutney.jpg",
  },
  {
    name: "Mango and Green Chilli",
    id: 23,
    img: "../images/sauces/Mango and Green Chilli.jpg",
    quantity: 1,
    price: "7$",
    image: "Mango and Green Chilli.jpg",
  },
  {
    name: "Mango Chutney",
    id: 24,
    img: "../images/sauces/Mango Chutney.jpg",
    quantity: 1,
    price: "8$",
    image: "Mango Chutney.jpg",
  },
  {
    name: "Onion Chutney",
    id: 25,
    img: "../images/sauces/Onion Chutney.jpg",
    quantity: 1,
    price: "6$",
    image: "Onion Chutney.jpg",
  },
  {
    name: "Red Chilli in Oil",
    id: 26,
    img: "../images/sauces/Red Chilli in Oil.jpg",
    quantity: 1,
    price: "7$",
    image: "Red Chilli in Oil.jpg",
  },
  {
    name: "Red Chilli Sauce",
    id: 27,
    img: "../images/sauces/Red Chilli Sauce.jpg",
    quantity: 1,
    price: "5$",
    image: "Red Chilli Sauce.jpg",
  },
  {
    name: "Spicy Banana Chutney",
    id: 28,
    img: "../images/sauces/Spicy Banana Chutney_.jpg",
    quantity: 1,
    price: "6$",
    image: "Spicy Banana Chutney_.jpg",
  },
  {
    name: "Spicy Cinnamon Spread",
    id: 29,
    img: "../images/sauces/Spicy Cinnamon Spread_.jpg",
    quantity: 1,
    price: "7$",
    image: "Spicy Cinnamon Spread_.jpg",
  },
  {
    name: "Spicy Mandarin Sauce",
    id: 30,
    img: "../images/sauces/Spicy Mandarin Sauce_.jpg",
    quantity: 1,
    price: "9$",
    image: "Spicy Mandarin Sauce_.jpg",
  },
  {
    name: "Spicy Olive Tapenad",
    id: 31,
    img: "../images/sauces/Spicy Olive Tapenad_.jpg",
    quantity: 1,
    price: "5$",
    image: "Spicy Olive Tapenad_.jpg",
  },
  {
    name: "Spicy Strawberry",
    id: 32,
    img: "../images/sauces/spicy_strawberry.jpg",
    quantity: 1,
    price: "6$",
    image: "spicy_strawberry.jpg",
  },
  {
    name: "Strawberry Chutney",
    id: 33,
    img: "../images/sauces/Strawberry Chutney.jpg",
    quantity: 1,
    price: "5$",
    image: "Strawberry Chutney.jpg",
  },
  {
    name: "Tomato Chutney",
    id: 34,
    img: "../images/sauces/Tomato Chutney.jpg",
    quantity: 1,
    price: "7$",
    image: "Tomato Chutney.jpg",
  },
  {
    name: "Very Spicy Mandarin Ajar",
    id: 35,
    img: "../images/sauces/Very Spicy Mandarin Ajar.jpg",
    quantity: 1,
    price: "6$",
    image: "Very Spicy Mandarin Ajar.jpg",
  },

  {
    name: "Akkedeneh and Lemon",
    id: 36,
    img: "../images/pickles/akkedeneh and lemon.jpg",
    quantity: 1,
    price: "5$",
    image: "akkedeneh and lemon.jpg",
  },
  {
    name: "Akkedeneh Pickles",
    id: 37,
    img: "../images/pickles/akkedeneh Pickles.jpg",
    quantity: 1,
    price: "6$",
    image: "akkedeneh Pickles.jpg",
  },
  {
    name: "Almond Pickles",
    id: 38,
    img: "../images/pickles/Almond Pickles.jpg",
    quantity: 1,
    price: "9$",
    image: "Almond Pickles.jpg",
  },
  {
    name: "Apple Pickles",
    id: 39,
    img: "../images/pickles/Apple Pickles(1).jpg",
    quantity: 1,
    price: "8$",
    image: "Apple Pickles(1).jpg",
  },
  {
    name: "Avocado Pickles",
    id: 40,
    img: "../images/pickles/Avocado Pickles(1).jpg",
    quantity: 1,
    price: "7$",
    image: "Avocado Pickles(1).jpg",
  },
  {
    name: "Beetroot",
    id: 41,
    img: "../images/pickles/beetroot_.jpg",
    quantity: 1,
    price: "6$",
    image: "beetroot_.jpg",
  },
  {
    name: "Cabbage and Carrot",
    id: 42,
    img: "../images/pickles/cabbage and carrot.jpg",
    quantity: 1,
    price: "5$",
    image: "cabbage and carrot.jpg",
  },
  {
    name: "Cabbage Pickles",
    id: 43,
    img: "../images/pickles/Cabbage Pickles.jpg",
    quantity: 1,
    price: "7$",
    image: "Cabbage Pickles.jpg",
  },
  {
    name: "Cauliflower Pickles",
    id: 44,
    img: "../images/pickles/Cauliflower Pickles.jpg",
    quantity: 1,
    price: "6$",
    image: "Cauliflower Pickles.jpg",
  },
  {
    name: "Cucumber",
    id: 45,
    img: "../images/pickles/cucumber.jpg",
    quantity: 1,
    price: "8$",
    image: "cucumber.jpg",
  },
  {
    name: "Dill Pickles",
    id: 46,
    img: "../images/pickles/Dill Pickles.jpg",
    quantity: 1,
    price: "5$",
    image: "Dill Pickles.jpg",
  },
  {
    name: "Egg Pickles",
    id: 47,
    img: "../images/pickles/Egg Pickles.jpg",
    quantity: 1,
    price: "4$",
    image: "Egg Pickles.jpg",
  },
  {
    name: "Fava Bean and Zaatar",
    id: 48,
    img: "../images/pickles/fava bean and zaatar.jpg",
    quantity: 1,
    price: "6$",
    image: "fava bean and zaatar.jpg",
  },
  {
    name: "Fava Beans Pickles",
    id: 49,
    img: "../images/pickles/Fava Beans Pickles.jpg",
    quantity: 1,
    price: "7$",
    image: "Fava Beans Pickles.jpg",
  },
  {
    name: "Fava Beans",
    id: 50,
    img: "../images/pickles/fava Beans.jpg",
    quantity: 1,
    price: "5$",
    image: "fava Beans.jpg",
  },
  {
    name: "Garlic Confit",
    id: 51,
    img: "../images/pickles/Garlic Confit.jpg",
    quantity: 1,
    price: "8$",
    image: "Garlic Confit.jpg",
  },
  {
    name: "Grape",
    id: 52,
    img: "../images/pickles/grape.jpg",
    quantity: 1,
    price: "6$",
    image: "grape.jpg",
  },
  {
    name: "Green Prunes Pickles",
    id: 53,
    img: "../images/pickles/Green Prunes Pickles.jpg",
    quantity: 1,
    price: "5$",
    image: "Green Prunes Pickles.jpg",
  },
  {
    name: "Green Tomato",
    id: 54,
    img: "../images/pickles/Green Tomato.jpg",
    quantity: 1,
    price: "6$",
    image: "Green Tomato.jpg",
  },
  {
    name: "Jalapeno Pickles",
    id: 55,
    img: "../images/pickles/Jalapeno Pickles.jpg",
    quantity: 1,
    price: "7$",
    image: "Jalapeno Pickles.jpg",
  },
  {
    name: "Lemon",
    id: 56,
    img: "../images/pickles/Lemon.jpg",
    quantity: 1,
    price: "5$",
    image: "Lemon.jpg",
  },
  {
    name: "Mango",
    id: 57,
    img: "../images/pickles/mango.jpg",
    quantity: 1,
    price: "9$",
    image: "mango.jpg",
  },
  {
    name: "Onion Pickles",
    id: 58,
    img: "../images/pickles/onion Pickles.jpg",
    quantity: 1,
    price: "5$",
    image: "onion Pickles.jpg",
  },
  {
    name: "Peach Pickles",
    id: 59,
    img: "../images/pickles/Peach Pickles.jpg",
    quantity: 1,
    price: "6$",
    image: "Peach Pickles.jpg",
  },
  {
    name: "Pear Pickles",
    id: 60,
    img: "../images/pickles/Pear Pickles.jpg",
    quantity: 1,
    price: "7$",
    image: "Pear Pickles.jpg",
  },
  {
    name: "Pumkin Pickles",
    id: 61,
    img: "../images/pickles/pumkin pickles.jpg",
    quantity: 1,
    price: "5$",
    image: "pumkin pickles.jpg",
  },
  {
    name: "Pumkin",
    id: 62,
    img: "../images/pickles/pumkin.jpg",
    quantity: 1,
    price: "6$",
    image: "pumkin.jpg",
  },
  {
    name: "Red Cauliflower Pickles",
    id: 63,
    img: "../images/pickles/Red Cauliflower Pickles.jpg",
    quantity: 1,
    price: "7$",
    image: "Red Cauliflower Pickles.jpg",
  },
];
export default productsToInsert;
